MAX_EMAIL_LENGTH= 254
MIN_USERNAME_LENGTH=1
MAX_USERNAME_LENGTH=30
MIN_NAME_LENGTH=1
MAX_NAME_LENGTH=30
MAX_BIO_LENGTH=400
MIN_ATTACHMENT_NAME_LENGTH=1
MAX_ATTACHMENT_NAME_LENGTH=25
MIN_CHALLENGE_NAME_LENGTH=1
MAX_CHALLENGE_NAME_LENGTH=30
MAX_CHALLENGE_DESCRIPTION_LENGTH=1000
MIN_PASSWORD_LENGTH=6
MIN_CATEGORY_LENGTH=1
MAX_CATEGORY_LENGTH=10
MIN_FLAG_LENGTH=1
MAX_FLAG_LENGTH=50
MIN_CHALLENGE_POINTS=0
MAX_CHALLENGE_POINTS=1000
EMAIL_REGEX='^[a-zA-Z0-9]+(?:\.[a-zA-Z0-9]+)*@[a-zA-Z0-9]+(?:\.[a-zA-Z0-9]+)*$'
MAX_ATTACHMENT_SIZE=20
CHALLENGE_SOLVED=0
INVALID_FLAG=1
CHALLENGE_ALREADY_SOLVED=2