version: "3.9"
services:
  apache:
    build: .
    container_name: apache
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - DB_HOST=db
    depends_on:
      - db
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html:ro
      - ./attachments:/var/www/attachments
      - ./config.json:/var/www/config.json:ro
      - ./logs.txt:/var/www/logs.txt

  db:
    image: mysql:8.0.31
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: S4943369
      MYSQL_USER: S4943369
      MYSQL_PASSWORD: test
