name: Deploy

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    deploy:
        permissions:
            contents: read

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              name: Checkout
            - uses: actions/setup-python@v4
              name: Install python
              with:
                  python-version: "3.10.8"
            - uses: Gr1N/setup-poetry@v7
              name: Setup poetry
            - uses: pnpm/action-setup@v2
              name: Setup pnpm
              with:
                  version: "7.14.2"
            - run: poetry install --with upload
              name: Install poetry dependencies
            - run: pnpm install
              name: Install pnpm dependencies
            - run: pnpm build
              name: Build
            - run: pnpm upload
              name: Upload
              env:
                  SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
